name: Java CI with Maven

on:
  push:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yaml
  pull_request:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v6
    - name: Import Secrets
      if: github.event_name != 'pull_request'
      id: secrets
      uses: hashicorp/vault-action@v3.4.0
      with:
        exportToken: true
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        role: cicd
        secrets: |
          kv/data/cicd/maven_central username | MAVEN_CENTRAL_USERNAME ;
          kv/data/cicd/maven_central password | MAVEN_CENTRAL_PASSWORD ;
          kv/data/cicd/gpg secring | GPG_SECRING ;
          kv/data/cicd/gpg passphrase | GPG_PASSPHRASE ;
    - name: Set up JDK 17
      if: github.event_name != 'pull_request'
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'liberica'
        cache: maven
        gpg-private-key: ${{ steps.secrets.outputs.GPG_SECRING }}
        gpg-passphrase: ${{ steps.secrets.outputs.GPG_PASSPHRASE }}
    - name: Set up JDK 17 (PR)
      if: github.event_name == 'pull_request'
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'liberica'
        cache: maven
    - name: Unit Tests
      run: ./mvnw -V --no-transfer-progress clean test
    - name: Generates Maven Settings
      if: github.event_name != 'pull_request'
      uses: s4u/maven-settings-action@v4.0.0
      with:
        servers: |
          [{
              "id": "central",
              "username": "${{ steps.secrets.outputs.MAVEN_CENTRAL_USERNAME }}",
              "password": "${{ steps.secrets.outputs.MAVEN_CENTRAL_PASSWORD }}"
          }]
    - name: Deploy to Maven Central
      if: github.event_name != 'pull_request'
      run: |
        set -e
        mvn -V \
            javadoc:jar \
            source:jar \
            package \
            org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign \
            deploy \
            --no-transfer-progress \
            -Dgpg.passphrase=${GPG_PASSPHRASE} \
            -DskipTests=true
    - name: Revoke token
      if: always() && github.event_name != 'pull_request'
      run: |
        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self || true
